version: "3.9"
services:
  db:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: infrafish-mailconfig
      POSTGRES_USER: mailconfig
      POSTGRES_PASSWORD: mailpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ifmc-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"

volumes:
  ifmc-db-data:
